[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
preDeployCommand = "npx prisma db push --skip-generate"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
